Mikal: Now parses queries

diff --git a/shdns/shdns b/shdns/shdns
--- a/shdns/shdns
+++ b/shdns/shdns
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# shdns: take a query and build a response
+
+##############################################################################
+# Utility functions
+##############################################################################
+
 # The state of a given bit in the byte
 dumpbit(){
   local temp
@@ -69,8 +75,151 @@ twiddlebit(){
   return $temp
 }
 
+# Read a single byte from a file
+readbyte(){
+  cat $1 | cut -b $2
+}
+
+# Read a single binary byte from a file
+readbytebinary(){
+  local temp
+
+  temp=`cat $1 | cut -b $2 | od -Ad -c | head -1 | tr -s " " | cut -f 2 -d " "`
+  if [ `echo $temp | cut -b 1` = "\\" ]
+  then
+    case `echo $temp | cut -b 2` in
+    0 ) temp="0";;
+    a ) temp="7";;
+    b ) temp="8";;
+    t ) temp="9";;
+    n ) temp="10";;
+    v ) temp="11";;
+    f ) temp="12";;
+    \\ ) temp="92";;
+    * ) echo "Error: Unknown escape binary sequence"; exit;;
+    esac
+  fi
+  
+  return $temp
+}
+
 ###############################################################################
 
+######################
+# Parse the input
+######################
+
+# Identification: 2 bytes
+id=`cat input | cut -b 1,2`
+echo "Packet id: $id"
+
+# Flags: 2 bytes
+temp=`cat input | cut -b 3 |  od -Ad -c | head -1 | cut -f 2 -d " "`
+testbit $temp 128; qr=$?
+testbit $temp 8; op=$?
+testbit $temp 4; aa=$?
+testbit $temp 2; trun=$?
+testbit $temp 1; rd=$?
+
+echo "Query / response: $qr"
+echo "Opcode: $op"
+echo "Authoritative answer: $aa"
+echo "Packet truncated: $trun"
+echo "Recursion desired: $rd"
+
+readbytebinary "input" 3; temp=$?
+testbit $temp 128; ra=$?
+
+echo "Recursion available: $ra"
+echo ""
+
+# The number of questions is the next two bytes
+readbytebinary "input" 5; topbyte=$?
+readbytebinary "input" 6; botbyte=$?
+qcount=$(( ($topbyte * 128) + $botbyte ))
+echo "Number of questions: $qcount"
+
+# The number of answers is the next two bytes
+readbytebinary "input" 7; topbyte=$?
+readbytebinary "input" 8; botbyte=$?
+acount=$(( ($topbyte * 128) + $botbyte ))
+echo "Number of answers: $acount"
+
+# The number of authority RRs is the next two bytes
+readbytebinary "input" 9; topbyte=$?
+readbytebinary "input" 10; botbyte=$?
+authcount=$(( ($topbyte * 128) + $botbyte ))
+echo "Number of authorities: $authcount"
+
+# The number of additional RRs is the next two bytes
+readbytebinary "input" 11; topbyte=$?
+readbytebinary "input" 12; botbyte=$?
+addcount=$(( ($topbyte * 128) + $botbyte ))
+echo "Number of additionals: $addcount"
+echo ""
+
+######################
+# For each question
+######################
+
+inset=13
+len=42
+questioncount=0
+
+while [ $questioncount -lt $qcount ]
+do
+  echo "Question"
+  echo -n "  "
+  name=""
+
+  while [ $len -gt 0 ]
+  do
+    # For each portion of the name
+    readbytebinary "input" $inset; len=$?
+    count=0
+    inset=$(( $inset + 1 ))
+
+    while [ $count -lt $len ]
+    do
+      char=`readbyte "input" $inset`
+      echo -n $char
+      name="$name$char"
+
+      inset=$(( $inset + 1 ))
+      count=$(( $count + 1 ))
+    done
+
+    echo -n " "
+    name="$name."
+  done
+
+  echo ""
+  # Type of question
+  readbytebinary "input" $inset; type=$?
+  echo -n "  Query type: "
+
+  case $type in
+  1 ) echo "A";;
+  2 ) echo "NS";;
+  5 ) echo "CNAME";;
+  12 ) echo "PTR";;
+  13 ) echo "HINFO";;
+  15 ) echo "MX";;
+  * ) echo "Error: Unknown query type"; exit;;
+  esac
+
+  # The class should always be 1
+  readbytebinary "input" $(( $inset + 1 )); class=$?
+  echo "  Query class: $class"
+
+  # Dodgy bug fix
+  name=`echo $name | sed 's/\.\.$//'`
+  
+  # Lookup the name in the db file
+  grep "$name" lookup | tr -s "\t" | cut -f 2
+
+  questioncount=$(( $questioncount + 1 ))
+done
 
 exit
 
