Mikal: It works!

diff --git a/shdns/shdns b/shdns/shdns
--- a/shdns/shdns
+++ b/shdns/shdns
@@ -93,21 +93,21 @@ readbytebinary(){
   local temp
 
   spinfor $1 $2 1000
-  temp=`cat $1 | cut -b $2 | od -Ad -c | head -1 | tr -s " " | cut -f 2 -d " "`
-  if [ `echo $temp | cut -b 1` = "\\" ]
-  then
-    case `echo $temp | cut -b 2` in
-    0 ) temp="0";;
-    a ) temp="7";;
-    b ) temp="8";;
-    t ) temp="9";;
-    n ) temp="10";;
-    v ) temp="11";;
-    f ) temp="12";;
-    \\ ) temp="92";;
-    * ) echo "Error: Unknown escape binary sequence"; exit;;
-    esac
-  fi
+  temp=`cat $1 | cut -b $2 | od -Ad -t u1 | head -1 | tr -s " " | cut -f 2 -d " "`
+#  if [ `echo $temp | cut -b 1` = "\\" ]
+#  then
+#    case `echo $temp | cut -b 2` in
+#    0 ) temp="0";;
+#    a ) temp="7";;
+#    b ) temp="8";;
+#    t ) temp="9";;
+#    n ) temp="10";;
+#    v ) temp="11";;
+#    f ) temp="12";;
+#    \\ ) temp="92";;
+#    * ) echo "Error: Unknown escape binary sequence"; exit;;
+#    esac
+#  fi
   
   return $temp
 }
@@ -138,8 +138,25 @@ writebinarybyte(){
 
 # Output the byte which is represented by a decimal number
 tobyte(){
+  local octal
+  local quotient
+  local remainder
+
   # Echo only takes octal numbers, so we convert
-  echo -n -e \\$1
+  quotient=$1
+  if [ $quotient -eq 0 ]
+  then
+    octal="0"
+  fi
+
+  while [ $quotient -ne 0 ]
+  do
+    remainder=$(( $quotient % 8 ))
+    octal="$remainder$octal"
+    quotient=$(( $quotient / 8 ))
+  done
+
+  echo -n -e \\$octal
 }
 
 ###############################################################################
@@ -149,7 +166,10 @@ process(){
   inset=$2
 
   # Identification: 2 bytes
-  id=`readstring $1 $inset 2`; inset=$(( $inset + 2 ))
+  readbytebinary "$1" $inset; idtopbyte=$?; inset=$(( $inset + 1 ))
+  readbytebinary "$1" $inset; idbotbyte=$?; inset=$(( $inset + 1 ))
+  logger "shdns $$ Packet id portions: $idtopbyte $idbotbyte"
+  id=$(( ($idtopbyte * 128) + $idbotbyte ))
   logger "shdns $$ Packet id: $id"
 
   # Flags: 2 bytes
@@ -219,10 +239,11 @@ process(){
       namelength=$(( $namelength + $len + 1 ))
       readbytebinary "$1" $inset; len=$?
     done
-    inset=$(( $inset + 2 ))
+    inset=$(( $inset + 1 ))
     logger "shdns $$ Lookup: $name"
   
-    # Type of question
+    # Type of question -- assume we only want the last byte for now...
+    inset=$(( $inset + 1 ))
     readbytebinary "$1" $inset; type=$?
     error="none"
     temp="shdns $$ Determine the query type"
@@ -236,10 +257,11 @@ process(){
     * ) temp="Error: Unknown query type"; error="yes";;
     esac
   
-    logger "$temp ($error)"
+    logger "$temp (error = $error)"
     inset=$(( $inset + 1 ))  
 
-    # The class should always be 1
+    # The class should always be 1 -- assume it's all in the last byte as well
+    inset=$(( $inset + 1 ))
     readbytebinary "$1" $inset; class=$?; inset=$(( $inset + 1 ))
     logger "shdns $$ Query class: $class"
   
@@ -249,57 +271,65 @@ process(){
       name=`echo $name | sed 's/\.$//'`
     
       # Lookup the name in the db file
-      result=`grep "$name" /home/mikal/opensource-unstable/shdns/lookup | tr -s "\t" | cut -f 2`
+      result=`grep "$name" /home/mikal/opensource/shdns/lookup | tr -s "\t" | cut -f 2`
       logger "shdns $$ Result: $result"
 
       #########################################################
       # Now we need to build a response to the query
 
       # The id number we were handed gets handed straight back
-      echo -n "$id"
+      tobyte $idtopbyte > /tmp/shdns-response-$$
+      tobyte $idbotbyte >> /tmp/shdns-response-$$
 
       # Flag this packet as being a reply (we currently never claim to be authoritive)
-      twiddlebit 0 128 1
-      tobyte $?
-#      tobyte 0
+      tobyte 128 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
 
       # Number of questions (we have to return the question we are answering)
-      tobyte 0
-      tobyte 1
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 1 >> /tmp/shdns-response-$$
  
       # Number of answers
-      tobyte 0
-      tobyte 1
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 1 >> /tmp/shdns-response-$$
 
       # Number of authorities
-      tobyte 0
-      tobyte 0
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
 
       # Number of additionals
-      tobyte 0
-      tobyte 0
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
 
       # It's easy to return the question, we just copy it...
-      echo -n `readstring $1 $questionstart $(( $inset - $questionstart - 2 ))`
-      tobyte 0
+      echo -n `readstring $1 $questionstart $namelength` >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte $type >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte $class >> /tmp/shdns-response-$$
+
+      # The domain name we are answering for in this answer
+      echo -n `readstring $1 $questionstart $namelength` >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
 
       # The type is the same as in the question
-      tobyte 0
-      tobyte $type
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte $type >> /tmp/shdns-response-$$
 
-      # The class is one
-      tobyte 0
-      tobyte 1
+      # The class is the same as well
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte $class >> /tmp/shdns-response-$$
 
       # The time to live is always low, because we are dodgy
-      tobyte 4
-      tobyte 4
-      tobyte 4
-      tobyte 4
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 4 >> /tmp/shdns-response-$$
 
       # The length of the returned data is always an IP (32 bits)
-      tobyte 0
-      tobyte 4
+      tobyte 0 >> /tmp/shdns-response-$$
+      tobyte 4 >> /tmp/shdns-response-$$
 
       # And now the answer as a number
       # For the result in the answer, we are going to need this in a binary form of decimal
@@ -307,12 +337,14 @@ process(){
       do
         temp=`echo $result | cut -f 1 -d "."`
         result=`echo $result | sed 's/^[0-9]*\.*//'`
-        tobyte $temp
+        tobyte $temp >> /tmp/shdns-response-$$
         logger "shdns $$ Processing result segment: $temp ($result)"
       done
 
       # We need to return an authority as well...
 
+      # And now we can send the result (done this way to make sure it is all in one packet)
+      cat /tmp/shdns-response-$$
       logger "shdns $$ Finished extracting result"
     else
       # Work out the erroneous type
